<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22328" started-at="2021-03-31T00:20:50 EDT" finished-at="2021-03-31T00:21:13 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22328" started-at="2021-03-31T00:20:50 EDT" finished-at="2021-03-31T00:21:13 EDT">
      <class name="test.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.LoginTest@131276c2]" name="setUp" is-config="true" duration-ms="5318" started-at="2021-03-31T00:20:50 EDT" finished-at="2021-03-31T00:20:56 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validUserShouldAbleToLogin()[pri:1, instance:test.LoginTest@131276c2]" name="validUserShouldAbleToLogin" duration-ms="5765" started-at="2021-03-31T00:20:56 EDT" finished-at="2021-03-31T00:21:02 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserShouldAbleToLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.LoginTest@131276c2]" name="tearDown" is-config="true" duration-ms="4735" started-at="2021-03-31T00:21:02 EDT" finished-at="2021-03-31T00:21:06 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.LoginTest@131276c2]" name="setUp" is-config="true" duration-ms="3798" started-at="2021-03-31T00:21:06 EDT" finished-at="2021-03-31T00:21:10 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="invalidUserShouldNotAbleToLogin()[pri:2, instance:test.LoginTest@131276c2]" name="invalidUserShouldNotAbleToLogin" duration-ms="1730" started-at="2021-03-31T00:21:10 EDT" finished-at="2021-03-31T00:21:12 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login - iBilling] but found [Dashboard- iBilling]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login - iBilling] but found [Dashboard- iBilling]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at page.LoginPage.validateDashboardHeader(LoginPage.java:47)
at test.LoginTest.invalidUserShouldNotAbleToLogin(LoginTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserShouldNotAbleToLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.LoginTest@131276c2]" name="tearDown" is-config="true" duration-ms="693" started-at="2021-03-31T00:21:12 EDT" finished-at="2021-03-31T00:21:13 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
